### ISSUE TITLE
Image API missing

### ISSUE THREAD

**Issue by dani-h** [marijnh/tern#615]
It seems like Tern has most of the browser/DOM API built in but is missing support for Image.
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/Image

Edit:
Actually it seems like Tern has most browser elements included in the definition file, but there is very little specialized information about each element, e.g the HTMLImageElement is missing `src` and `alt`. They are all of the type Element and they all contain the same information. Is there any way to inherit the prototype from Element, but specialize the prototype in the json definition files? I'd like to add `src`, `onload`, `onerror` to the HTMLImageElement and also add a constructor for `Image()` that returns a new HTMLImageElement.

I've made a PR to include the Image() constructor in #616

**Comment by marijnh** [comment]
Fixed via #616

**Comment by dani-h** [comment]
@marijnh Is it possible to have specific attributes on the HTMLImageElement while extending from Element in a definition file? Can you show a quick example?

**Comment by marijnh** [comment]
Tern treats all Elements as being of the same type. The reason for this is that most sources of Element values (`childNodes`, `querySelector`, `parentElement`, etc) don't distinguish between the various sub-types of Element or Node, and thus, if we moved things like `src` and `getContext` to specific (image or canvas) elements, we'd lose completion and typing for them in 99% of cases.

**Comment by dani-h** [comment]
Ah, makes sense.
However if I were to write my own little library and had an inheritance chain, how could I write definitions for that? Can type A inherit from type B and still have something specific in it's prototype?

**Comment by marijnh** [comment]
Yes. You can see for example the way Element inherits from Node in `browser.json` -- its `prototype` object has a `"!proto": "Node.prototype"` declaration.

**Comment by dani-h** [comment]
Ah! Thanks!

**Comment by angelozerr** [comment]
@dani-h I have written https://github.com/angelozerr/tern-browser-extension whioch extends browser definition to use it inside HTML and gives extra features like elements ids (document.getElementById), CSS selectors (for document.querySelectors) and document.getElementById, document.createElement is able to returns the well instance of Element. So we could support your case : 

```html
<img id="MyImg"" src="..." />
<script>
var img  =document.getElementById("MyImg");
img. // here completions shows src
```

To do that I must overrid eteh original browser.json to had src inside HTMLImgElement inside `preLoadDef` https://github.com/angelozerr/tern-browser-extension/blob/master/browser-extension.js#L320

If you are nterested, any contribution are welcome!

**Comment by dani-h** [comment]
@angelozerr Looks nice at first glance. I'll try it out. Does it only support inline scripts?

**Comment by angelozerr** [comment]
Pay attention, I have not tested with the ternjs in the master (I will do that soon).

> Does it only support inline scripts?

You mean JavaScript inside on* attributes? If it that it support it, but this is not managed.

**Comment by dani-h** [comment]
No, all of your examples on the page display scripts in lined with HTML. Does it support standalone js files that are loaded?

**Comment by angelozerr** [comment]
You mean have completion for HTML element ids inside a script a.js which is included inside an HTML file. If it that, no, but I think we could support it (by showing teh whole ids of the HTML files).

I suggest you that you create issues at https://github.com/angelozerr/tern-browser-extension/issues to avoid disturbing tern project.
